version: '3.8'

services:
    pos:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                VARIANT: 17.1-bullseye
                USERNAME: node
        init: true
        env_file:
            - ../.env
            # - ../.env.local
        volumes:
            - ..:/workspace:cached
        command: sleep infinity
        user: node
